BAV/Controllers/BAVController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using SharedObjects.ValueObjects;
using SharedObjects.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Linq;
using System.Threading.Tasks;

namespace BAV.Controllers
{
    [Authorize]
    public class BAVController : Controller
    {
        private readonly IBAVService bAVService;
        private ADODB.Recordset rs = new ADODB.Recordset();

        public BAVController(IBAVService bAVService)
        {
            this.bAVService = bAVService;
        }

        public async Task<IActionResult> Configuration()
        {
            //OleDbDataAdapter dataAdapter = new OleDbDataAdapter();
            //DataTable dt = new DataTable();
            //JEMS_3.CR_Assemblies cr = new JEMS_3.CR_Assemblies();
            ////rs = cr.ListByCustomer("VNHCMM0MSSQLV1A", "JEMS", 6511, 14);
            //rs = cr.ListActive("VNHCMM0MSSQLV1A", "JEMS", 6511);
            //dataAdapter.Fill(dt, rs);
            //List<VJEMS> list = new List<VJEMS>();
            //for (int i = 0; i < dt.Rows.Count; i++)
            //{
            //    VJEMS t = new VJEMS()
            //    {
            //        Customer = dt.Rows[i]["Customer"].ToString().Trim(),
            //        Number = dt.Rows[i]["Number"].ToString().Trim(),
            //        Revision = dt.Rows[i]["Revision"].ToString(),
            //        Family = dt.Rows[i]["Family"].ToString(),
            //        Assembly = dt.Rows[i]["Assembly"].ToString(),
            //    };
            //    list.Add(t);
            //}
            //ViewData["list"] = list;

            var model = new BAVViewModel();
            model.Model = null;
            model.Revision = null;
            var results = await bAVService.Configuration_getall(model);
            ViewData["data"] = results;
            return View();
        }
        public async Task<IActionResult> Configuration_add([FromBody] BAVViewModel model)
        {
            var results = await bAVService.Configuration_add(model);
            return Json(new { results = results });
        } 
        public async Task<IActionResult> Configuration_delete([FromBody] BAVViewModel model)
        {
            var results = await bAVService.Configuration_delete(model);
            return Json(new { results = results });
        }
        public async Task<IActionResult> Configuration_Get([FromBody] BAVViewModel model)
        {
            var results = await bAVService.Configuration_get(model);
            return PartialView(results);
        }
        public async Task<IActionResult> Configuration_getall([FromBody] BAVViewModel model)
        {
            var results = await bAVService.Configuration_getall(model);
            return PartialView(results);
        }
        public async Task<IActionResult> Configuration_count([FromBody] BAVViewModel model)
        {
            var count = await bAVService.Configuration_count(model);
            return Json(new { result = count });
        }
    }
}

BAV/Views/Shared/_Layout.cshtml
@using SharedObjects.Extensions;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->

    <link href="~/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN Excel download -->
    <script src="~/js/filesaver.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js"></script>
    <!-- END Excel download -->


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">BAV</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BAV" asp-action="Configuration">Configuration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="log" asp-action="get">Log</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("SYSTEM ADMIN"))
                            {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="admin" asp-action="get">Administration</a>
                        </li>
                        }
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {

                <a asp-action="Logout" asp-controller="Account" id="userinfo" data-user="@User.GetSpecificClaim("Ntlogin")" data-display-name="@User.GetSpecificClaim("UserName")" data-email="@User.GetSpecificClaim("UserEmail")">
                    <p> Hi @User.GetSpecificClaim("UserName") (@User.GetSpecificClaim("Ntlogin"))</p>
                    <i class="icon-key"></i> Log Out
                </a>
                }
                else
                {
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; BAV (Box Accessory Verification) <a href="http://vnhcmm0teapp03/JVNTestSupport/Home.aspx#">JVN TE Web Page</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/assets/global/plugins/jquery.min.js"></script>
    <script src="~/js/jquery-validation/jquery.validate.min.js"></script>



    <script src="~/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="~/assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>


    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="~/assets/global/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="~/assets/global/scripts/metronic.js" type="text/javascript"></script>
    <script src="~/assets/admin/layout3/scripts/layout.js" type="text/javascript"></script>
    <script src="~/assets/admin/layout3/scripts/demo.js" type="text/javascript"></script>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- BEGIddsdsdsN PAGE LEVEL SCRIPTS -->
    <script>
        jQuery(document).ready(function () {
            Metronic.init(); // init metronic core components
            Layout.init(); // init current layout
            Demo.init(); // init demo features
        });
    </script>

    <script src="~/js/bootbox.js/bootbox.js"></script>
    <script src="~/js/jquery-validation/jquery.validate.js"></script>
    <script src="~/js/twbs-pagination/jquery.twbsPagination.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>